### ISSUE TITLE
Ideas proyecto?

### ISSUE THREAD

**Issue by ower89** [SalesianosTrianaDAM/Hackathon2k14#2]
Hola. ha llegado la hora de asignar a cada equipo un proyecto por favor que el responsable de cada equipo ponga un comentario que contenga lo siguiente:

- Responsable del equipo
- Miembros del equipo
- Proyecto (por ejemplo web de noticias)

**Comment by ivanalbizu** [comment]
* Componentes del tercer grupo:
  - Ivor Somrenburg
  - Ruben Sedeño
  - Francisco Barrera
  - Iván González (Responsable)

* Idea de proyecto:
  - Simular el registro de alumnos de un centro educativo. Existirá alumnos registrados a un curso con asignaturas. La ampliación podría ser asociarle profesores y sus asignaturas...

**Comment by spachecojimenez** [comment]
Hola, me parece bien la idea. Como le hemos recomendado a los otros equipos, empezad por lo básico y seguir avanzando poco a poco. 
Remo esta de acuerdo con la idea también.
