### ISSUE TITLE
Debuggear condición en Handlebars

### ISSUE THREAD

**Issue by ialex90** [SalesianosTrianaDAM/Hackathon2k14#5]
Me he leído el enlace de chrome oficial para debugging y he buscado en la red pero no encuentro nada.

Me gustaría poner una condición en un template de handlebars para que según la condición inyecte un código u otro... pero el tema es que en la consola de chrome la carpeta templates con todos los hbs no están... ¿Cómo lo puedo hacer?

**Comment by ower89** [comment]
Buenas y feliz año. Conseguiste solucionar el problema?

**Comment by ialex90** [comment]
Buenas, feliz año igualmente

Pues la verdad es que no, estuvimos buscando e intentando lo que dijiste pero no hemos conseguido solucionarlo, pero es extraño... porque en otros archivos hbs, la condición {{# if isAdmin}} funciona bien, para hacer comprobaciones, pero en el header.hbs no funciona...

No tiene mucho sentido pero hemos probado los if/else if y {{#if ../isAdmin) pero sin éxito...

**Comment by ower89** [comment]
Haz una cosa, crea un repositorio publico y sube todo el codigo y cuando sergio y yo tengamos un rato lo miramos en casa. Pon aqui que controlador y vista es la que esta dando problemas para que podamos encontrarlo... pasanos la URL del repositorio por aqui cuando lo tengas.

**Comment by ialex90** [comment]
Repositorio : https://github.com/ialex90/Hackathon2k14
El problema es que en el header.hbs no podemos usar la condición isAdmin, y tampoco podemos debuggear porque en la consola no se visualiza la carpeta con los templates de handlebars.

Saludos!

**Comment by spachecojimenez** [comment]
Que quereis hacer ahi con el isAdmin? la template header.hbs no tiene ninguna condicion, imagino que la habeis comiteado asi para que funcione el proyecto, donde iria el isAdmin?

**Comment by ialex90** [comment]
Pues arreglar el fallo del inicio de sesión.

Resulta de que cuando inicias sesión el botón se cambia a cerrar sesión, ok. Si recargas la web, el botón vuelve a cambiar a "iniciar sesión". Entonces, queremos meter una condición de si isAdmin el botón no cambie a "iniciar sesión", no sé si me explico pero es difícil explicarlo escribiendo :)
Si no, te lo intento explicar de otra forma.

Por eso había pensado meter una condición ahí.

**Comment by isramartinez** [comment]
Donde tenéis la función para loguear y crear la sesión? No la veo por ningun lado.
Para hacer lo que queréis tenéis que loguear al usuario y crearle la sesión, y en la template de handlebars comprobar si esta o no logueado y si es admin o no para pintar una cosa u otra.

**Comment by spachecojimenez** [comment]
@ower89 no tiene acceso a github, pero me ha enviado esta respuesta (no esta testeada): 

### /backend/controllers/user_controller.js

En la demo puedes hacer ```http://localhost:8080/api/users``` y devuelve todos los usuarios eso no tiene sentido y es un peligro para la seguridad pero era una demo asi que no nos molestamos en solucionarlo
lo que si tiene sentido es que cuando llames a ```http://localhost:8080/api/users``` te de los datos de TU usaurio cuando esta logueado, puedes conseguir eso cambiando el filter:

```
UserController.prototype.get = function (req, res)
{
    var query, filter;

    // buscamos usuario con id del usuario logueado o con id 0 (no existe)
    filter = {
      _id : req.session.userId || 0
    };

    userModel.find(filter, null, null, function(error, docs) {
        if(error === null)
        {
            res.send(200, { user : docs[0] || null });
        }
        else
        {
            console.log(error);
            res.send(500, 'Internal Server Error');
        }
    });
};
```
Despues de hacer eso llama a ```http://localhost:8080/api/users``` y mira si devuelve tu usuario cuando estas logueado y ```null``` cuando no estas logueado

### Header View

Para poder hacer un {{#if}} en handlebars necesitamos un modelo que contenga algo. Para ver si la session esta abierta o cerrada yo no utilizaria ```isAdmin``` utilizaria ```{{#if user}}```
asi que lo primero es pasarle un modelo a la vista ```userModel``` eso internamente llamara a  ```http://localhost:8080/api/users``` y devuelve un objeto con la porpiedad```user``` o ```null```

```
define([ 'js/framework/framework.view', 'js/models/user_model' ], function (View, userModel) {
    'use strict';

    var headerView = new View({
        container : "#header",
        templateUrl : "js/templates/header.hbs",
        model : userModel, // necesitas pasar algun JSON a la template apra poder hacer {{#if foo}} vamos a pasar null (cuando el usuario no esta logueado) y un objeto que contiene los datos del usuario logueado (cuando estas logueado)
        parseArgs : function(){
            return {};
        }
    });

    return headerView;
});
```


### Header template

Finalmente en la template utilizamos el objeto con la porpiedad```user``` o ```null``` para mostrar un enlace u otro.

```
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <span class="navbar-brand" >
                <i class="fa fa-book"></i>
                SPA Hackathon
            </span>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="#home/index">
                        <i class="fa fa-home"></i> Home
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                 {{#if user}}
                   <li class="hide" id="login-btn">
                             <a href="#account/login">
                                       <i class="fa fa-key"></i> Iniciar Sesion
                             </a>
                   </li>
                   <li class="" id="logout-btn">
                             <a href="#account/logout">
                                       <i class="fa fa-sign-out"></i> Cerrar Sesion
                             </a>
                   </li>
                 {{else}}
                   <li class="" id="login-btn">
                             <a href="#account/login">
                                       <i class="fa fa-key"></i> Iniciar Sesion
                             </a>
                   </li>
                   <li class="hide" id="logout-btn">
                             <a href="#account/logout">
                                      <i class="fa fa-sign-out"></i> Cerrar Sesion
                             </a>
                   </li>
                 {{/if}}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
```

**Comment by ialex90** [comment]
Vale, lo que no entendía es que tenía que pasarle el modelo en el view, ahora si me encaja.
Una duda es si tbm tengo que cambiar el api/publications, porque me interesa y mucho tener un lugar donde acceder a todas las publicaciones.

**Comment by remojansen** [comment]
Tio perdona pero yo he estado sin acceso a github al final he tenido que crear otra cuenta... seguramente es demasiado tarde pero el api/publications no tienes que tocarlo porque tienen sentido que devuelva todas las publicaciones lo que no tiene sentido es que devuelva todos los ususarios. Imagina si yo entro en wwww.elmundo.es/api/users y me devuelve todos los usuarios con todas las contraseña eso es un fallo de seguridad pero entrar en wwww.elmundo.es/api/noticias y que devuelva todas las noticias tiene sentido.

**Comment by remojansen** [comment]
@ialex90  se soluciono tu problema? podemos cerrar la issue?

**Comment by ialex90** [comment]
Si, cerramos, pero no pude solucionarlo... no pude dedicarle tiempo :(
