### ISSUE TITLE
Guardar variable Handlebars en variable javascript

### ISSUE THREAD

**Issue by ialex90** [SalesianosTrianaDAM/Hackathon2k14#6]
Buenas tardes,

Necesitamos guardar una variable de hbs en un var de javascript. Pongo un ejemplo y el fallo al que no le encontramos solución.

var texto = {{content}};

Error : (Mirando la consola, vemos como content contiene punto y aparte entonces se vería en consola algo así)

var texto = "Este es el texto que queremos volcar.... klajflkjdkljfskljf skljgfklsd.(Aquí está el problema)
klfjgklfdjg dfkljgkldfjg ldfkjgldflk";

Hemos intentado con jQuery la función $.parseHTML y varias cosas más, pero sin solución...

¿Alguna idea? Graciass

**Comment by isramartinez** [comment]
Javascript trata los retornos de carro (saltos de linea) como \s, es decir un texto con un salto de linea en JS debe verse tal que así:

    var textoConSalto = "Hola esto es una linea.\nY esta es una nueva linea";

Con eso JS ya sabra que tiene que pintar un salto de linea.

**Comment by ialex90** [comment]
Buenas Israel, si eso ya lo sabía pero creo que no me expliqué correctamente.
El problema me viene porque {{content}} me da texto con saltos de línea y al ponerle delante un var texto = {{content}} no me captura todo el texto que devuelve content, ya que si hay un salto de línea se me sale a la siguiente línea, provocando un error en la consola de js.

![errorjs](https://cloud.githubusercontent.com/assets/5755545/5615420/6ac80f4c-94fb-11e4-9640-257cac59678d.png)

**Comment by isramartinez** [comment]
Ok ahora si entiendo a lo que te referías. Eso te va a pasar siempre haciendolo de esa manera. Has probado con triple llave en lugar de doble llave? 
    {{{content}}}
Eso te debe dar el contenido integro de la variable sin "ser limpiado" por el compilador de handlebars.

Prueba con eso y me dices que devuelve (con suerte aqui devuelve el salto de linea como \n y puedes guardar la variable con var texto = "{{{content}}}", de todos modos no se hasta que punto el enfoque que le estais dando es bueno, no debería meterse código JS en una template de handlebars...

**Comment by ialex90** [comment]
Pues lo probé cuando estuve buscando información y lo he vuelto a probar y nada... sigue lanzando el mismo error:

Uncaught SyntaxError: Unexpected token :

y la misma foto que arriba... Pues supongo que no será el mejor sitio para alojar código javascript pero bueno, la verdad para lo que quiero hacer, creo que es la mejor manera, aunque de javascript esté frito :)

**Comment by ower89** [comment]
Buenas veo en tu ejemplo que tienes:

```var texto = {{content}};```

Y ```content``` tiene como valor ```Exodus: Dioses y reyes...``` eso se convierte en:

```var texto = Exodus: Dioses y reyes...```

Como es logico eso esta fallando porque deberia ser un string:

```var texto = "Exodus: Dioses y reyes...";```

Aun asi eso te va a dar problemas por los saltos de linea. Yo recomiendo utilizar un input hidden:

```<input type="hidden" value="{{content}}" id="foo"/>```

Cuando te haga falta puedes acceder al valor con:

```var texto = $("#foo").val();```

**Comment by spachecojimenez** [comment]
Solucionastes ya el fallo? yo veo lo mismo que remo, estabas poniendo el string sin comillas.

A parte, estoy de acuerdo con @isramartinez , en una template de handlebars no puede ir codigo javascript. Funciona, pero no deberias. 

Una de las cosas fundamentales del proyecto es que cada archivo tenga lo que debe llevar (los .html solo html, las template solo html y handlebars y los javascript solo javascript), porque, cuando te enfrentes a un proyecto de verdad, es la unica manera de que sea mantenible el codigo. Ademas nosotros vamos a mirar tambien que el codigo este bien separado y tendra un valor en la puntuacion.

Si no sabes donde colocarias un archivo o un trozo de codigo, comentalo y te podremos guiar.

**Comment by isramartinez** [comment]
Exacto, no se exactamente que estas intentando consgeuir para tener que hacerlo de esa manera, pero seguramente se pueda enfocar de otra modo que sea mas mantenible.

**Comment by ialex90** [comment]
Pues seguramente se pueda enfocar de otra forma pero es la primera vez que trabajamos (al menos yo) con javascript, node, handlebars y demás... y sólo con que me saliera, era un éxito jaja pero bueno, ya que estamos lo dejamos bien, ¿Dónde me aconsejáis que puedo meter ese código js? La función js lo que hace a grosso modo es coger un campo de mi modelo de la BD y acortarlo (Como una short description) no sé si sería mejor que se añada como campo de la BD al crear al json... ¿Noo?

**Comment by ialex90** [comment]
Sería duplicar código pero más rapidez, eso sería la teoría de trabajo que seguimos con json en la BD, no?? Gracias!

**Comment by ialex90** [comment]
Entonces la solución de @ower89 no es válida no? :(

**Comment by isramartinez** [comment]
Para acortar el texto lo que haría yo es crear un helper de handlebars que hiciera exactamente eso, se le pase el valor y lo devuelva acortado. Ejemplo:

    //Declaramos el helper
    Handlebars.registerHelper('shortContent', function(content) {
      return content.substr(0, 250) ;
    });

Y para usarlo seria:
    <p>{{shortContent content}}</p>
Siendo "shortContent" la llamada al helper que hemos declarado y "content" lo que le queremos pasar para que lo acorte.

**Comment by ialex90** [comment]
Vale, lo reviso Isra, tiene muy buena pinta eso jeje, gracias por la pronta respuesta ;)

**Comment by isramartinez** [comment]
Nada ;)

**Comment by ialex90** [comment]
Vale, pero tendría que importar el helper en el handlebars no? Eso si se puede hacer no?

**Comment by ialex90** [comment]
Vale, pero tendría que importar el helper no? Eso si se puede hacer en el handlebars?

**Comment by ialex90** [comment]
Vale, vale, encontré la forma perfecta! Gracias :)
