### ISSUE TITLE
Creación de usuarios

### ISSUE THREAD

**Issue by ialex90** [SalesianosTrianaDAM/Hackathon2k14#8]
Buenas, a pocos días de la entrega no terminamos de cuajar la creación de usuarios por un problema bastante raro.

La cosa es que el usuario es creado, e insertado en la base de datos, pero se cae la web... por un momento se cae, entonces hay que reiniciar la conexión por consola y ya entonces ese usuario se puede loguear. De hecho, es insertado sin problemas en la BD.

¿a qué puede ser esto debido?

**Comment by remojansen** [comment]
Eso es que esta sucediendo algo que lanza una excepcion y como no la habeis controlado, la excepcion esta haciendo que el proceso de el servidor de node pare de ejecutarse...

Estas creando un usuario asi que entiendo que estais haciendo un ```HTTP POST```

En ```UserController``` estais usando ```UserController.prototype.post()``` me imagino como en el ejemplo:

```
UserController.prototype.post = function (req, res)
{
    var user;

    user = new userModel({
        email : req.body.email,
        password : req.body.password,
        isAdmin : false
    });

    user.save(function(error) {
        if(error === null)
        {
            res.send(200, { user : [] });
        }
        else
        {
            console.log(error);
            res.send(500, 'Internal Server Error');
        }
    });
};
```

Asegurate de que estas llamando a ese metodo cuando haces un ```POST``` por ```AJAX```. y intenta poner un try/catch:

```
UserController.prototype.post = function (req, res)
{
    try
    {
      /* copiar de arriba la logica */ 
    }
    catch(e)
    {
        console.log(error);
        res.send(500, 'Internal Server Error');
   }
};
```

La forma mas facil de ver donde peta va a ser debuggear paso a paso la aplicacion node.js con WebStorm (https://www.jetbrains.com/webstorm/features/#nodejs).

**Comment by ialex90** [comment]
Vale perfecto, ya no peta, vi el error, Gracias¡¡
