### ISSUE TITLE
Entregas

### ISSUE THREAD

**Issue by remojansen** [SalesianosTrianaDAM/Hackathon2k14#9]
## Requisitos entrega

Cuando esteis listos para enviar lo que tengais (no tiene porque estar terminado) poner un comentario aqui junto con la siguiente infromacion:

- Equipo (A, B o C)
- El link del repositorio de github
- Script de creacion (Abajo teneis un ejemplo)
- Cuentarnos un poco de que va cuestra app?, que querias hacer al principio?,que cosas no habeis podido terminar? que destacariais de vuestra app? Y que os ha parecido en general Node.js, mongo DB y MVC en el cliente? y cualquier otra cosa que os parezca interesante mencionar.
- Comentar un poco que nos recomendarias hacer el año que viene para futuros alumnos, os ha parecido interesante? os a parecido facil o dificil? ...

### A
- Jose Antonio Navarro
- Santiago Vicente
- Yafar Campos
- Alejandro Quevedo
- Alejandro Lora (Responsable)

### B
- J. Antonio Rivas
- Carlos Romero
- Ricardo López
- David Solsona (Responsable)

### C
- Ivor Somrenburg
- Ruben Sedeño
- Francisco Barrera
- Iván González (Responsable)

## Ejemplo script de creacion
Creamos una base de datos para que la applicacion funcione correctamente la primera vez que la abrimos, algo parecido a lo sigueinte.
```
use nombreDeLaBaseDeDatos
db.createCollection("user")
db.user.insert({ nombre : "remo", apellido: "jansen" })
db.createCollection("recetas")
db.recetas.insert({ titulo: "tortilla de patatas", ingredientes: [] /*...*/ })
```

**Comment by ialex90** [comment]
Nosotros tenemos la base de datos en un servidor (monogolab) quieres que te pasemos el usuario y pass de la cuenta, para ir viendo los cambios en la BD ??

**Comment by remojansen** [comment]
Si la aplicacion me la bajo y la cadena de conexion esta ya puesta para apuntar a monogolab y no tengo que ningun insert ni nada incluso mejor :)

**Comment by ialex90** [comment]
- Equipo A
- https://github.com/ialex90/Hackathon2k14
- BD en mongoLab (User: josenr Pass: 1deberMAS) - https://mongolab.com/

Nuesta app sería una aplicación para gestionar un blog de películas. Los admin, pueden:

- Crear nuevas entradas (Películas).
- Añadir su título, contenido, director y url de imagen de portada o trailer. (Esta puede ser internar al sevidor, en la ruta /img/Photo.jpg y rellenándolo así ó una url de una imagen externar al servidor, contemplando para su mejor visualización 800x400).
- Modificar dichos datos desde admin.
- Crear cuentas de usuarios y loguearse.
- Corta el texto del contenido en la página principal si es muy largo, al estilo WP

Nos hemos quedado con ganas de meter algunas mejoras básicas como:

- Si no está logueado que no pueda comentar.
- En el registro, recoger nickname y foto avatar para mostrarla en los comentarios.
- La insercción de vídeo-trailer.

Y como mejora difíciles ( a nuestro nivel) hubiera sido:

- Filtar por directores, géneros o fechas.
- Puntuar y poder filtrar también por puntuaciones.
- Navegación con <<1 2 3 4 >> para las entradas, y tenerlas de 10 en 10 o como el usuario elija.

Destacamos que es un estilo WP para manejar de forma fácil un blog de la temática, en este caso, cinematográfica.

Pensamos que mongo DB es muy redundante pero muy rápida y fácil de usar, es decir, el formato JSON nos parece un acierto y la rapidez con la que se trabaja es la necesaria para una web de rápida respuesta. Conforme al MVC en el cliente, es fantástico, todo se desarrolla ahí, y se va cargando conforme vallas navegando el contenido requerido. Queda muy muy rápido la navegación y una muy buena experiencia de usuario.

Comentar que nos hubiera gustado tener a la mano dos cosas: tiempo y conocimiento. No teníamos ni IDEA de javascript, y esto así de sopetón ha sido difícil de digerir. Creo que en esta profesión es necesario tener una buena adaptación a tecnologías nuevas o desconocidas, claro que sí, pero partiendo de la base de formarte para aquello en lo que vas a trabajar previamente, aunque sean nociones... Es muy difícil darle a alguien un proyecto android, sin conocer java. Y del tiempo, ni hablamos. Lo que hemos podido sacar ha sido gracias al trabajo por parte del equipo en las vacaciones de navidades, porque desde que llegamos ha sido imposible dedicarle algo de tiempo.

¿Parecer difícil? Creemos que teniendo más nivel de JS no es difícil esto que se pedía.

Para otro año, no recomiendo hacer esto en esta fecha, creo que no es compatible con el ritmo de trabajo del curso que estamos ejerciendo, porque nos hemos quedado "a medias" con ganas de aprender, de hacer y entender más cosas.

De parte del equipo muchas gracias por resolvernos las dudas, por apostar por nosotros y por atendernos tan rápido como habéis podido. Una grata experiencia. @remojansen @spachecojimenez @gon250 @isramartinez

**Comment by ialex90** [comment]
¿Se han entregado los 3 proyectos? ¿Se sabe alguna fecha aprox. para las valoraciones/apuntes/comentarios?

**Comment by remojansen** [comment]
Buenas, estamos teniendo una semana con poco tiempo libre asi que de momento no hemos podido mirar anda pero lo miraremos lo antes posible... perdon por haceros esperar...
